version: '3.8'

services:
  alexandrCluster-2024-postgres:
    image: postgres:16.1
    ports:
      - '${POSTGRES_PORT:-5432}:5432'
    environment:
      POSTGRES_USER: '${POSTGRES_USER:-alexandr}'
      POSTGRES_PASSWORD: '${POSTGRES_PASSWORD:-alexandrpassword}'
      POSTGRES_DB: '${POSTGRES_DB:-alexandrCluster-2024}'
    volumes:
      - ./alexandrCluster-2024-api-db:/var/lib/postgresql/alexandrCluster-2024

  alexandrCluster-2024-redis:
    image: redis:7.2.3
    ports:
      - '${REDIS_PORT:-6379}:6379'
    command: >
      --requirepass '${REDIS_PASSWORD:-alexandrredispass}'
    restart: unless-stopped

  alexandrCluster-2024-s3:
    image: quay.io/minio/minio:latest
    command: server /data --console-address ":9001"
    restart: unless-stopped
    ports:
      - "8000:9000"
      - "8001:9001"
    volumes:
      - ./alexandrCluster-2024-api-s3-data:/usr/src/app/s3
    environment:
      MINIO_ROOT_USER: '${AWS_S3_ACCESS_KEY:-alxndrACkey}'
      MINIO_ROOT_PASSWORD: '${AWS_S3_SECRET_KEY:-alxndrSEkey}'

volumes:
  alexandrCluster-2024-api-db:
  alexandrCluster-2024-api-s3: